### ISSUE TITLE
[REQUEST] Ability to disable the Magic Bar

### ISSUE THREAD

**Issue by Valkyrie1676** [Uri6/Genius-Enhancer#102] opened 2024-05-04 04:27 UTC
**Valkyrie1676** (optional)

**Feature Description**
When I try to add metadata at the album level and make typos the magic bar pops up and to get it off my screen so I can see it escapes all my progress in adding metadata.

**Comment by RDIL** [comment] 2024-05-04 12:20
duplicate of #95

**Closed as not planned by RDIL** 2024-05-04 12:20 UTC
Labels: enhancement
